# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

xcode_workspace: Example/blockbased-delegates.xcodeproj # path to your xcodeproj folder
xcode_scheme: blockbased-delegates-Example

script:
- set -o pipefail && xcodebuild test -workspace Example/blockbased-delegates.xcworkspace -scheme blockbased-delegates-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
